window.ATLIS_PROPOSALS = {
  "42": {
    "number": 42,
    "name": "Ortodoncia Gemma Martínez Asúnsolo",
    "shortName": "Ortodoncia Gemma Martínez Asúnsolo",
    "brand": "ORTODONCIA GEMMA MARTÍNEZ ASÚNSOLO",
    "domain": "www.ortodonciamartinezasunsolo.com",
    "source": "https://www.ortodonciamartinezasunsolo.com/",
    "sourceContact": "https://www.ortodonciamartinezasunsolo.com/contacto/",
    "pageType": "renovada",
    "pageLabel": "Landing renovada",
    "pageDescription": "Una propuesta de nueva primera pantalla y recorrido sencillo de solicitud.",
    "waStatus": "Canal hipotético; confirmar si la clínica usa WhatsApp",
    "waMode": "por_validar",
    "improvement": "Renovar la primera pantalla y guiar una solicitud de valoración con horario preferido.",
    "observation": "El título principal de la portada es el número de teléfono; falta una propuesta clara que explique al paciente cómo iniciar una valoración de ortodoncia.",
    "headline": "Ortodoncia que empieza por conocerte.",
    "subtitle": "Una primera visita clara con el equipo de Gemma Martínez Asúnsolo.",
    "eyebrow": "PROPUESTA DE PÁGINA · VALENCIA",
    "features": [
      "Especialidad en ortodoncia",
      "Valencia",
      "Formulario de contacto"
    ],
    "topic": "valoración de ortodoncia",
    "sectionTitle": "El siguiente paso, sin fricción.",
    "sectionCopy": "Una propuesta de nueva primera pantalla y recorrido sencillo de solicitud. Recepción conserva la confirmación de cada visita.",
    "caseLabel": "conversación de ejemplo",
    "time": "18:42",
    "request": "Valoración de ortodoncia",
    "preference": "Tardes, por confirmar",
    "patient": "Hola, me gustaría pedir una valoración de ortodoncia.",
    "reply": "Hola, soy un asistente virtual ilustrativo de Ortodoncia Gemma Martínez Asúnsolo. Puedo recoger tu solicitud de valoración de ortodoncia para que la revise recepción. ¿Qué días o franja te vienen bien?",
    "patientTwo": "Preferiría la tarde, si es posible.",
    "replyTwo": "Gracias. He anotado tu preferencia. Recepción comprobará la disponibilidad y te confirmará la cita. La valoración clínica la hará el equipo profesional.",
    "webQuestion": "¿Puedo solicitar una valoración de ortodoncia desde aquí?",
    "webReply": "Sí. Puedo recoger el motivo general y tu preferencia horaria para recepción. El equipo confirmará la disponibilidad y hará cualquier valoración clínica.",
    "webChips": [
      "Pedir cita",
      "Horarios",
      "Contactar con recepción"
    ],
    "palette": 2
  },
  "43": {
    "number": 43,
    "name": "Clínica Dental Such",
    "shortName": "Such",
    "brand": "SUCH",
    "domain": "www.clinicadentalsuch.com",
    "source": "https://www.clinicadentalsuch.com/",
    "sourceContact": "https://www.clinicadentalsuch.com/contacto/",
    "pageType": "especialidad",
    "pageLabel": "Página de especialidad",
    "pageDescription": "Una entrada enfocada en el motivo de consulta, conectada con la web actual.",
    "waStatus": "Canal publicado; automatización pendiente de aprobación",
    "waMode": "visible",
    "improvement": "Asistente web que responda dudas administrativas y entregue solicitudes ordenadas a recepción.",
    "observation": "La portada reúne mucha información útil; el paso entre leer sobre un tratamiento y solicitar una visita puede hacerse más corto.",
    "headline": "De la información a tu primera valoración.",
    "subtitle": "Clínica Such acompaña la decisión sin pedirte que elijas un tratamiento por tu cuenta.",
    "eyebrow": "PROPUESTA DE PÁGINA · VALENCIA",
    "features": [
      "Equipo visible",
      "Tratamientos detallados",
      "WhatsApp disponible"
    ],
    "topic": "valoración de ortodoncia",
    "sectionTitle": "El siguiente paso, sin fricción.",
    "sectionCopy": "Una entrada enfocada en el motivo de consulta, conectada con la web actual. Recepción conserva la confirmación de cada visita.",
    "caseLabel": "conversación de ejemplo",
    "time": "18:42",
    "request": "Valoración de ortodoncia",
    "preference": "Tardes, por confirmar",
    "patient": "Hola, me gustaría pedir una valoración de ortodoncia.",
    "reply": "Hola, soy un asistente virtual ilustrativo de Such. Puedo recoger tu solicitud de valoración de ortodoncia para que la revise recepción. ¿Qué días o franja te vienen bien?",
    "patientTwo": "Preferiría la tarde, si es posible.",
    "replyTwo": "Gracias. He anotado tu preferencia. Recepción comprobará la disponibilidad y te confirmará la cita. La valoración clínica la hará el equipo profesional.",
    "webQuestion": "¿Puedo solicitar una valoración de ortodoncia desde aquí?",
    "webReply": "Sí. Puedo recoger el motivo general y tu preferencia horaria para recepción. El equipo confirmará la disponibilidad y hará cualquier valoración clínica.",
    "webChips": [
      "Pedir cita",
      "Horarios",
      "Contactar con recepción"
    ],
    "palette": 3
  },
  "44": {
    "number": 44,
    "name": "ODONTOLOGY IGS CLINIC",
    "shortName": "ODONTOLOGY IGS CLINIC",
    "brand": "ODONTOLOGY IGS CLINIC",
    "domain": "odontologyclinic.com",
    "source": "https://odontologyclinic.com/",
    "sourceContact": "https://odontologyclinic.com/contacto/",
    "pageType": "ajuste",
    "pageLabel": "Ajuste de la web",
    "pageDescription": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa.",
    "waStatus": "Canal hipotético; confirmar si la clínica usa WhatsApp",
    "waMode": "por_validar",
    "improvement": "Revisar el recorrido de contacto y añadir un asistente para consultas administrativas, conservando la identidad actual.",
    "observation": "La página de contacto promete respuesta al escribir, llamar o rellenar un formulario, pero el formulario no apareció en la extracción de la página; hay que comprobar su carga y experiencia real en móvil.",
    "headline": "Tecnología y calma desde el primer contacto.",
    "subtitle": "Una solicitud simple para que el equipo de Odontology pueda continuar la conversación.",
    "eyebrow": "PROPUESTA DE PÁGINA · VALENCIA",
    "features": [
      "Enfoque digital",
      "Equipo multidisciplinar",
      "Valencia"
    ],
    "topic": "primera valoración",
    "sectionTitle": "El siguiente paso, sin fricción.",
    "sectionCopy": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa. Recepción conserva la confirmación de cada visita.",
    "caseLabel": "conversación de ejemplo",
    "time": "18:42",
    "request": "Primera valoración",
    "preference": "Tardes, por confirmar",
    "patient": "Hola, me gustaría pedir una primera valoración.",
    "reply": "Hola, soy un asistente virtual ilustrativo de ODONTOLOGY IGS CLINIC. Puedo recoger tu solicitud de primera valoración para que la revise recepción. ¿Qué días o franja te vienen bien?",
    "patientTwo": "Preferiría la tarde, si es posible.",
    "replyTwo": "Gracias. He anotado tu preferencia. Recepción comprobará la disponibilidad y te confirmará la cita. La valoración clínica la hará el equipo profesional.",
    "webQuestion": "¿Puedo solicitar una primera valoración desde aquí?",
    "webReply": "Sí. Puedo recoger el motivo general y tu preferencia horaria para recepción. El equipo confirmará la disponibilidad y hará cualquier valoración clínica.",
    "webChips": [
      "Pedir cita",
      "Horarios",
      "Contactar con recepción"
    ],
    "palette": 4
  },
  "45": {
    "number": 45,
    "name": "Centro Odontológico Carmen Domingo",
    "shortName": "Carmen Domingo",
    "brand": "CARMEN DOMINGO",
    "domain": "carmendomingocentroodontologico.com",
    "source": "https://carmendomingocentroodontologico.com/",
    "sourceContact": "https://carmendomingocentroodontologico.com/contacto/",
    "pageType": "ajuste",
    "pageLabel": "Ajuste de la web",
    "pageDescription": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa.",
    "waStatus": "Canal publicado; automatización pendiente de aprobación",
    "waMode": "visible",
    "improvement": "Convertir consultas entrantes en solicitudes con contexto y mantener la confirmación en recepción.",
    "observation": "El acceso rápido a WhatsApp no recoge por sí mismo el motivo ni la preferencia de la visita antes de llegar al equipo.",
    "headline": "Pide tu primera visita con tranquilidad.",
    "subtitle": "El equipo de Carmen Domingo recibe una solicitud clara desde el primer mensaje.",
    "eyebrow": "PROPUESTA DE PÁGINA · VALENCIA",
    "features": [
      "Centro odontológico",
      "WhatsApp directo",
      "Formulario de contacto"
    ],
    "topic": "primera visita",
    "sectionTitle": "El siguiente paso, sin fricción.",
    "sectionCopy": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa. Recepción conserva la confirmación de cada visita.",
    "caseLabel": "conversación de ejemplo",
    "time": "18:42",
    "request": "Primera visita",
    "preference": "Tardes, por confirmar",
    "patient": "Hola, me gustaría pedir una primera visita.",
    "reply": "Hola, soy un asistente virtual ilustrativo de Carmen Domingo. Puedo recoger tu solicitud de primera visita para que la revise recepción. ¿Qué días o franja te vienen bien?",
    "patientTwo": "Preferiría la tarde, si es posible.",
    "replyTwo": "Gracias. He anotado tu preferencia. Recepción comprobará la disponibilidad y te confirmará la cita. La valoración clínica la hará el equipo profesional.",
    "webQuestion": "¿Puedo solicitar una primera visita desde aquí?",
    "webReply": "Sí. Puedo recoger el motivo general y tu preferencia horaria para recepción. El equipo confirmará la disponibilidad y hará cualquier valoración clínica.",
    "webChips": [
      "Pedir cita",
      "Horarios",
      "Contactar con recepción"
    ],
    "palette": 0
  },
  "46": {
    "number": 46,
    "name": "Déniz Clínica Dental",
    "shortName": "Déniz Clínica Dental",
    "brand": "DÉNIZ CLÍNICA DENTAL",
    "domain": "denizclinicadental.com",
    "source": "https://denizclinicadental.com/",
    "sourceContact": "https://denizclinicadental.com/contacto/",
    "pageType": "ajuste",
    "pageLabel": "Ajuste de la web",
    "pageDescription": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa.",
    "waStatus": "WhatsApp publicado; automatización propuesta",
    "waMode": "visible",
    "improvement": "Corregir enlaces y simplificar la solicitud de cita, con respuesta inicial a dudas administrativas.",
    "observation": "El código público de contacto contiene un enlace de correo de plantilla «contact@mysite.com», aunque la clínica publica su correo real; conviene corregir ese detalle antes de captar más tráfico.",
    "headline": "Una cita sencilla, con trato personal.",
    "subtitle": "La experiencia Déniz empieza antes de llegar a la clínica de Ruzafa.",
    "eyebrow": "PROPUESTA DE PÁGINA · VALENCIA",
    "features": [
      "Clínica en Ruzafa",
      "Formulario de contacto",
      "Equipo cercano"
    ],
    "topic": "primera visita",
    "sectionTitle": "El siguiente paso, sin fricción.",
    "sectionCopy": "Una evolución puntual de la página actual, sin plantear una reconstrucción completa. Recepción conserva la confirmación de cada visita.",
    "caseLabel": "conversación de ejemplo",
    "time": "18:42",
    "request": "Primera visita",
    "preference": "Tardes, por confirmar",
    "patient": "Hola, me gustaría pedir una primera visita.",
    "reply": "Hola, soy un asistente virtual ilustrativo de Déniz Clínica Dental. Puedo recoger tu solicitud de primera visita para que la revise recepción. ¿Qué días o franja te vienen bien?",
    "patientTwo": "Preferiría la tarde, si es posible.",
    "replyTwo": "Gracias. He anotado tu preferencia. Recepción comprobará la disponibilidad y te confirmará la cita. La valoración clínica la hará el equipo profesional.",
    "webQuestion": "¿Puedo solicitar una primera visita desde aquí?",
    "webReply": "Sí. Puedo recoger el motivo general y tu preferencia horaria para recepción. El equipo confirmará la disponibilidad y hará cualquier valoración clínica.",
    "webChips": [
      "Pedir cita",
      "Horarios",
      "Contactar con recepción"
    ],
    "palette": 1
  }
};
